package Utils;

public enum OpzioneMenu {
    AGGIUNGI_ISCRITTO,
    CERCA_ISCRITTO,
    RIMUOVI_ISCRITTO,
    VISUALIZZA_ISCRITTI,
    AGGIUNGI_ABBONAMENTO,
    TERMINA_ABBONAMENTO,
    VISUALIZZA_ABBONAMENTI_ATTIVI,
    VISUALIZZA_STORICO_ABBONAMENTI
}
